###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

based_on_package: "xarm7_config"

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    # Specify any additional parameters required for the URDF.
    # [Optional]
    urdf:
      package: "xarm7_sim_config"
      path: "description/picknik_xarm.xacro"
    urdf_params:
      - launch_ros2_control: "false"
      - launch_mujoco: "true"

# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
      - "moveit_studio::behaviors::ConverterBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    base_objectives:
      package_name: "xarm_base_config"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "xarm7_config"
    relative_path: "waypoints/waypoints.yaml"
