controller_manager:
  ros__parameters:
    update_rate: 150  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    velocity_force_controller:
      type: velocity_force_controller/VelocityForceController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      joint1:
        goal: 0.05
      joint2:
        goal: 0.05
      joint3:
        goal: 0.05
      joint4:
        goal: 0.05
      joint5:
        goal: 0.05
      joint6:
        goal: 0.05
      joint7:
        goal: 0.05        

servo_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      joint1:
        goal: 0.05
      joint2:
        goal: 0.05
      joint3:
        goal: 0.05
      joint4:
        goal: 0.05
      joint5:
        goal: 0.05
      joint6:
        goal: 0.05
      joint7:
        goal: 0.05

velocity_force_controller:
  ros__parameters:
    planning_group_name: manipulator
    sensor_frame: link_eef
    ee_frame: link_pose_jog
    max_joint_velocity:
      - 0.524
      - 0.524
      - 0.524
      - 1.047
      - 1.047
      - 1.047
      - 1.047
    max_joint_acceleration:
      - 52.4
      - 52.4
      - 52.4
      - 52.4
      - 52.4
      - 52.4
      - 52.4
    max_cartesian_velocity:
      - 0.25
      - 0.25
      - 0.25
      - 1.5707
      - 1.5707
      - 1.5707
    max_cartesian_acceleration:
      - 20.0
      - 20.0
      - 20.0
      - 40.0
      - 40.0
      - 40.0