###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

based_on_package: "xarm_base_config"

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  simulated: False
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    # Specify any additional parameters required for the URDF.
    # [Optional]
    urdf_params:
      - name: "xarm7"
      - dof: "7"
      - robot_type: "xarm"
      - ros2_control_plugin: "uf_robot_hardware/UFRobotSystemHardware"
      - robot_ip: "0.0.0.0" #USe a real IP here

# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
      - "moveit_studio::behaviors::ConverterBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    base_objectives:
      package_name: "xarm_base_config"
      relative_path: "objectives"    
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "xarm7_config"
    relative_path: "waypoints/waypoints.yaml"
