###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Set simulated to false if you are using this as a configuration for real hardware.
  # This allows users to switch between mock and real hardware by changing a single parameter with config inheritance.
  # [Required]
  simulated: True

  # If the MoveIt Pro Agent should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: True

  # If the MoveIt Pro Agent should launch the robot state publisher.
  # This should be false if you are launching the robot state publisher as part of drivers.
  # [Optional, default=True]
  launch_robot_state_publisher: True

  # Specify additional launch files for running the robot with real hardware.
  # [Optional, defaults to a blank launch file if not specified]
  robot_driver_persist_launch_file:
    package: "xarm_base_config"
    path: "launch/robot_drivers_to_persist.launch.py"

  # Specify any additional launch files for running the robot in simulation mode.
  # Used when hardware.simulated is True.
  # [Optional, defaults to a blank launch file if not specified]
  simulated_robot_driver_persist_launch_file:
    package: "xarm_base_config"
    path: "launch/sim/robot_drivers_to_persist_sim.launch.py"
  simulated_hardware_launch_file:
    package: "moveit_studio_agent"
    path: "launch/blank.launch.py"

  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "xarm_base_config"
      path: "description/picknik_xarm.xacro"
    srdf:
      package: "xarm_base_config"
      path: "config/moveit/xarm.srdf.xacro"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the UR descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      - name: "xarm"
      - prefix: ""
      - hw_ns: "xarm"
      - limited: "false"
      - effort_control: "false"
      - velocity_control: "false"
      - add_gripper: "false"
      - add_vacuum_gripper: "false"
      - add_bio_gripper: "false"
      - load_gazebo_plugin: "false"
      - ros2_control_plugin: "mock_components/GenericSystem"
      - ros2_control_params: ""
      - add_realsense_d435i: "false"
      - add_d435i_links: "false"
      - robot_ip: ""
      - report_type: "normal"
      - robot_sn: ""
      - use_gazebo_camera: "false"
      - mesh_suffix: "stl"
      - kinematics_suffix: ""

# Sets ROS global params for launch.
# [Optional]
ros_global_params:
  # Whether or not to use simulated time.
  # [Optional, default=False]
  use_sim_time: False

# Configuration files for MoveIt.
# For more information, refer to https://moveit.picknik.ai/main/doc/how_to_guides/moveit_configuration/moveit_configuration_tutorial.html
# [Required]
moveit_params:
  # Used by the Waypoint Manager to save joint states from this joint group.
  joint_group_name: "xarm7"

  ompl_planning:
    package: "xarm_base_config"
    path: "config/moveit/ompl_planning.yaml"
  stomp_planning:
    package: "xarm_base_config"
    path: "config/moveit/stomp_planning.yaml"
  kinematics:
    package: "xarm_base_config"
    path: "config/moveit/pose_ik_distance.yaml"
  servo:
    package: "xarm_base_config"
    path: "config/moveit/servo.yaml"
  sensors_3d:
    package: "xarm_base_config"
    path: "config/moveit/sensors_3d.yaml"    
  joint_limits:
    package: "xarm_moveit_config"
    path: "config/xarm7/joint_limits.yaml"
  pose_jog:
    package: "xarm_base_config"
    path: "config/moveit/pose_jog.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

# Configuration for launching xarm_base_config processes.
# [Required, if using xarm_base_config]
ros2_control:
  config:
    package: "xarm_base_config"
    path: "config/control/controllers.yaml"
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "joint_trajectory_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  # [Optional, default=[]]
  controllers_inactive_at_startup:
    - "servo_controller"
    - "velocity_force_controller"
  # Any controllers here will not be spawned by MoveIt Pro.
  # [Optional, default=[]]
  controllers_not_managed: []
  # Optionally configure remapping rules to let multiple controllers receive commands on the same topic.
  # [Optional, default=[]]
  controller_shared_topics: []

# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
      - "moveit_studio::behaviors::ConverterBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    simulation_objectives:
      package_name: "xarm_base_config"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "xarm_base_config"
    relative_path: "waypoints/waypoints.yaml"
